service: s3-signing

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::stories.underlunchers.co.uk/*"


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post
          cors: true

#resources:
#  Resources:
#    UploadBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: stories.underlunchers.co.uk
#        AccessControl: PublicRead
#        CorsConfiguration:
#          CorsRules:
#          - AllowedMethods:
#            - GET
#            - PUT
#            - POST
#            - HEAD
#            AllowedOrigins:
#            - "*"
#            AllowedHeaders:
#            - "*"